/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package day1

import java.io.File

class Elf(num: Int) {
	val num = num
	var food = mutableListOf<Int>()
	val totalCals: Int
		get() { return this.food.toList().sum() }
}

class App {
	fun elfsCalories(input: List<String>): List<Elf> {
	    var elfs = mutableListOf<Elf>()
	    val iterator = input.listIterator()
	    var elfCounter = 1
	    while(iterator.hasNext()) {
		    val elf = Elf(elfCounter)
		    var calories = iterator.next()
		    while(calories.toIntOrNull() != null){
		    	elf.food.add(calories.toIntOrNull()!!)
			if(iterator.hasNext()) calories = iterator.next()
			else break
		    }
		    if(!elf.food.isEmpty()) { 
			    elfs.add(elf)
			    elfCounter = elfCounter + 1
		    }
	    }
	    return elfs.toList()
	}

        fun findCalorieRichElf(input: List<Elf>, numOfElves: Int): Int {
        	val elves = input.sortedWith(compareBy { it.totalCals }).takeLast(numOfElves)
		return elves.map { it.totalCals }.sum()
	}
}

var input = """1000
2000
3000

4000

5000
6000

7000
8000
9000

10000"""

fun readFileInLines(fileName: String): List<String> = File(fileName).useLines { it.toList() }

fun main() {
    val realInput = readFileInLines("input.txt")
    val elfs = App().elfsCalories(realInput)
    println(elfs.size)
    println(App().findCalorieRichElf(elfs, 3))
}
