/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package day3

import java.io.File

class RuckSack(fullSack: String) {
	val fullSack = fullSack
	var sack1: String
	var sack2: String
	init {
		sack1 = this.fullSack.substring(0, this.fullSack.length/2)
		sack2 = this.fullSack.substring(this.fullSack.length/2)
	}
	fun findSame(): String {
		sack1.forEach { it -> if(sack2.contains(it.toString(), ignoreCase = false)) return it.toString() }
		return ""
	}
}

fun inputFromAdvent(fileName:String): List<String> {
	return File(fileName).useLines { it.toList() }
}

fun getScoreMap() : HashMap<String, Int> {
	var map : HashMap<String, Int> = HashMap<String, Int>()
	var char = 'A'
	for (i in 27..52) {
		map.put("$char",i)
		++char
	}
	char = 'a'
	for(i in 1..26) {
		map.put("$char",i)
		++char
	}
	return map
}


fun main() {
    var sacks = inputFromAdvent("input.txt")
    val scoreMap: HashMap<String, Int> = getScoreMap()
    var score = 0
    sacks.forEach { it -> score = score + scoreMap.get(RuckSack(it).findSame())!! }
    println(score)
}
